### ISSUE TITLE
About the problems encountered in reproduction

### ISSUE THREAD

**Issue by AntyRia** [visresearch/patchmix#3]
When I was trying to reproduce kNN Evaluation, I wanted to ask what should be the placement format of the dataset? Can you give me an example?

Note: I have configured all paths into corresponding files in the config folder

When I downloaded the CIFAR100 dataset to /xxxx/.... When running the example under /cifar100/, the train folder is not found

I downloaded the CIFAR100 dataset to /xxxx/.... /cifar100/train/ gives me an error when I try to execute the code

`Traceback (most recent call last):
  File "main_knn.py", line 339, in <module>
    main_ddp(args)
  File "main_knn.py", line 321, in main_ddp
    mp.spawn(eval_knn, args=(args,), nprocs=args.world_size)
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/hiyan/tyh_workspace/patchmix/main_knn.py", line 88, in eval_knn
    train_features, test_features, train_labels, test_labels = extract_feature_pipeline(
  File "/home/hiyan/tyh_workspace/patchmix/main_knn.py", line 108, in extract_feature_pipeline
    dataset_train = build_dataset(is_train=True, args=args)
  File "/home/hiyan/tyh_workspace/patchmix/main_knn.py", line 30, in build_dataset
    dataset = ImageFolderInstance(
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/home/hiyan/miniconda3/envs/codecflow/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in /home/hiyan/tyh_workspace/patchmix/dataset/cifar-100/train.
`

**Comment by sccbhxc** [comment]
Due to the compatibility to ImageNet-1K, we adopt `ImageFolder` as the dataset to read images. Hence, for CIFAR dataset, you need to transform the CIFAR dataset to `*.png` image formats as the one required by `ImageFolder` .
We will also plan to add direct support for raw CIFAR dataset.
