### ISSUE TITLE
state_dict = checkpoint['state_dict']

### ISSUE THREAD

**Issue by CachCheng** [visresearch/patchmix#4]
=> loading checkpoint 'weights/vit-small-300-82.8.pth'
Traceback (most recent call last):
  File "/home/cash/SW/pycharm-community-2021.1.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/cash/SW/pycharm-community-2021.1.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/source_code/CNN/patchmix/main_finetune.py", line 433, in <module>
    main_ddp(args)
  File "/data/source_code/CNN/patchmix/main_finetune.py", line 185, in main_ddp
    main(args.rank, args)
  File "/data/source_code/CNN/patchmix/main_finetune.py", line 254, in main
    state_dict = get_model_from_frame(checkpoint, args)
  File "/data/source_code/CNN/patchmix/main_finetune.py", line 86, in get_model_from_frame
    state_dict = checkpoint['state_dict']
TypeError: 'VisionTransformerMoCo' object is not subscriptable

**Comment by CachCheng** [comment]
我在finetune的时候加载模型vit-small-300-82.8.pth，直接报错了，是加载的不对么，还请不吝赐教？

**Comment by CachCheng** [comment]
已解决！
